// This file is generated by PortraitImporter.py automatically. Don't edit it.

#pragma once

#include "FE7JPortrait.h"
#include "FE7JStructDef.h"
#include "Gba_video.h"

extern const unsigned short Fenrir_portrait_palette[];
extern const unsigned char Fenrir_portrait_tileset[];
extern const unsigned short Fenrir_portrait_oam_right[];
extern const unsigned short Fenrir_portrait_oam_left[];
extern const unsigned short Fenrir_portrait_in_status_screen_tsa[];
extern const unsigned short Fenrir_portrait_in_status_screen_alpha[][10];
