// This file is generated by PortraitImporter.py automatically. Don't edit it.
// {Fenrir_portrait_tileset, Fenrir_portrait_mini, Fenrir_portrait_palette, Fenrir_portrait_mouth_frame, {&Fenrir_eye_frame_info}, 8, 56, 0, 0, 3, oam_id, tsa_id, mask_id, 1}, // Fenrir

#pragma once

#include "FE7JPortrait.h"
#include "FE7JStructDef.h"

extern const unsigned short Fenrir_portrait_palette[];
extern const unsigned char Fenrir_portrait_tileset[];
extern const unsigned short Fenrir_portrait_oam_right[];
extern const unsigned short Fenrir_portrait_oam_left[];
extern const unsigned short Fenrir_portrait_in_status_screen_tsa[];
extern const unsigned short Fenrir_portrait_in_status_screen_mask[][10];
extern const unsigned char Fenrir_portrait_mouth_frame[][32 * 16 / 2];
extern const unsigned char Fenrir_portrait_mini[];
extern const struct EyeFrameInfo Fenrir_eye_frame_info;
