-- 32色动画sheet导入gba，生成双调色板
-- by laqieer
-- 2017/9/15

require "GBAImage"

if(arg[1] == nil)
then
	print([[Import a 32-color battle animation sheet into GBA
	
Usage: lua 32ColorSheetMaker.lua name [options]
	
	Options:
		-f	Set the format of sheet images. (Default is PNG.)
]])
	os.exit(-1)
end

function getFileName(filename)
	return string.gsub(filename,".+[/\\]","")
end

name = arg[1]

imageFormat = 'PNG'

if(arg[2] == '-f')
then
	imageFormat = arg[3]
end

sheets = {}
sheetID = 0
repeat
	sheetID = sheetID + 1
	sheets[sheetID] = im.FileImageLoad(name..'_sheet_'..sheetID..'.'..imageFormat)
until(sheets[sheetID] == NULL)
sheets[sheetID] = nil

for sheetID, sheet in pairs(sheets) do
	if(sheet:ColorSpace() ~= im.MAP)
	then
		print('Error: '..name..'_sheet_'..sheetID..'.'..imageFormat..' is not indexed')
		os.exit(-1)
	end
end

pal = sheets[1]:GetPalette()

out = io.open(name..'_sheet.c','w')
if(out == nil)
then
	print('Error: cannot create file '..name..'_sheet.c')
	os.exit(-1)
end
out:write([[// Generated by 32ColorSheetMaker
// ]]..os.date("%Y/%m/%d %H:%M:%S")..'\n\n')
out:write('// 基本调色板\n')
out:write('const unsigned short '..getFileName(name)..'_pal[] = {\n\t')
for colorID = 0, 15 do
	out:write(string.format('0x%04X, ', GBAImage:color2gba(pal[colorID])))
end
out:write('\n};\n\n')
out:write('// 扩展调色板\n')
out:write('const unsigned short '..getFileName(name)..'_palEx[] = {\n\t')
out:write(string.format('0x%04X, ', GBAImage:color2gba(pal[0])))
for colorID = 0, 14 do
	out:write(string.format('0x%04X, ', GBAImage:color2gba(pal[colorID + 16])))
end
out:write('\n};\n\n')
for sheetID, sheet in pairs(sheets) do
	out:write('const unsigned char '..getFileName(name)..'_sheet_'..sheetID..'[] = {\n\t')
	for lin = sheet:Height() - 1, 0, -8 do
		for col = 0, sheet:Width() - 1, 8 do
			palID = 0
			for y0 = 0, 8 - 1 do
				for x0 = 0, 8 / 2 - 1 do
					pixelL = sheet[0][lin - y0][col + 2 * x0]
					pixelR = sheet[0][lin - y0][col + 2 * x0 + 1]
					palID2 = palID
					if(pixelL > 0)
					then
						palID2 = 1
						if(pixelL > 15)
						then
							palID2 = 2
							pixelL = pixelL - 15
						end
					end
					if(palID2 ~= palID)
					then
						if(palID == 0)
						then
							palID = palID2
						else
							print('Error: tile ('..col..','..sheet:Height() - 1 - lin..') has colors from different palettes')
							os.exit(-1)
						end
					end
					if(pixelR > 0)
					then
						palID2 = 1
						if(pixelR > 15)
						then
							palID2 = 2
							pixelR = pixelR - 15
						end
					end
					if(palID2 ~= palID)
					then
						if(palID == 0)
						then
							palID = palID2
						else
							print('Error: tile ('..col..','..sheet:Height() - 1 - lin..') has colors from different palettes')
							os.exit(-1)
						end
					end
					out:write(string.format('0x%02X, ', pixelL + pixelR * 0x10))
				end
			end
			out:write(' // tile ('..col..','..sheet:Height() - 1 - lin..')')
			if(palID == 1)
			then
				out:write(' pal')
			end
			if(palID == 2)
			then
				out:write(' palEX')
			end
			out:write('\n')
		end
	end
	out:write('\n};\n\n')
end
out:close()
