# Import customized size portrait
# by laqieer
# 2019-4-3

import GBAImage
import os
import sys
import getopt
import operator
from PIL import Image, ImageColor
import json


class ImageSizeError(Exception):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def __str__(self):
        return "Wrong image size: %dx%d" % (self.width, self.height)


def main(argv):
    tileset_file = argv[1]
    template_file = argv[2]
    try:
        opts, args = getopt.getopt(argv[3:], "hcbt:n:s:",
                                   ["help", "source", "binary", "transparent=", "name=", "status_screen="])
    except getopt.GetoptError:
        print("%s <tileset_file> <template_file> -h" % argv[0])
        sys.exit(2)
    transparent_color = ImageColor.getrgb("#a0c898")
    no_check_transparent_color = False
    output_c = False
    output_bin = False
    file_base = os.path.splitext(tileset_file)[0]
    portrait_name = os.path.split(file_base)[1]
    portrait_in_status_screen_file = None
    for opt, arg in opts:
        if opt in ["-h", "--help"]:
            print("Import customized size portrait.")
            print("%s <tileset_file> <template_file> [-h] [-c] [-b] [-t #rrggbb] [-n name] [-s <image_file>]" % argv[0])
            print("<tileset_file>: 256x32 image")
            print("<template_file>: json file to config template")
            print("-h,--help: show help information")
            print("-c,--source: output C source file")
            print("-b,--binary: output binary file")
            print("-t,--transparent: transparent color (default: #a0c898)."
                  "Set to nocheck if you have placed the transparent color to the first slot in the palette")
            print("-n,--name: portrait name")
            print("-s,--status_screen: portrait in status screen. 80x72 image")
        elif opt in ["-c", "--source"]:
            output_c = True
        elif opt in ["-b", "--binary"]:
            output_bin = True
        elif opt in ["-t", "--transparent"]:
            if arg == "nocheck":
                no_check_transparent_color = True
            else:
                transparent_color = ImageColor.getrgb(arg)
        elif opt in ["-n", "--name"]:
            portrait_name = arg
            file_base = os.path.join(os.path.split(tileset_file)[0], portrait_name)
        elif opt in ["-s", "--status_screen"]:
            portrait_in_status_screen_file = arg
    im = Image.open(tileset_file)
    if not operator.eq(im.size, (256, 32)):
        raise ImageSizeError(im.width, im.height)
    if im.mode != "P":
        im = im.convert("P", palette=Image.ADAPTIVE, colors=16)
    if len(im.getpalette()) > 16 * 3:
        im = im.quantize(16)
    if (not no_check_transparent_color) and (not operator.eq(transparent_color, tuple(im.getpalette()[:3]))):
        for i in range(16):
            if operator.eq(transparent_color, tuple(im.getpalette()[3 * i: 3 * i + 3])):
                dest_map = [i]
                for j in range(i):
                    dest_map.append(j)
                for j in range(i + 1, 16):
                    dest_map.append(j)
                im = im.remap_palette(dest_map)
                break
    palette = GBAImage.Palette(im.getpalette())
    palette.resize(16)
    tileset = GBAImage.TileSet(im)
    with open(template_file, 'r') as f:
        template = json.load(f)
    if portrait_in_status_screen_file is not None:
        im_ss = Image.open(portrait_in_status_screen_file)
        if not operator.eq(im_ss.size, (80, 72)):
            raise ImageSizeError(im_ss.width, im_ss.height)
        status_screen_portrait_map = GBAImage.BGMap(im_ss, im.getpalette(), tileset)
    # parse template
    portrait_width = template["width"]
    portrait_height = template["height"]
    oam_right = []
    oam_left = []
    for obj in template["OBJ"]:
        width = obj["width"]
        height = obj["height"]
        x_coordinate = obj["x"] - portrait_width // 2
        y_coordinate = obj["y"] - portrait_height + 80
        tile_number = 32 * obj["tile_y"] + obj["tile_x"]
        oam_right.append(GBAImage.OBJAttribute(tile_number, x_coordinate, y_coordinate, width, height))
        x_coordinate = - (x_coordinate + width)
        oam_left.append(GBAImage.OBJAttribute(
            tile_number, x_coordinate, y_coordinate, width, height, horizontal_flip=1))
    # output C source
    if output_c:
        comment = "// This file is generated by " + os.path.split(argv[0])[1] + " automatically. Don't edit it.\n"
        header_file = file_base + ".h"
        with open(header_file, 'w') as f:
            f.write(comment)
            f.write("""
#pragma once

#include "FE7JPortrait.h"
#include "FE7JStructDef.h"
#include "Gba_video.h"

""")
            f.write("extern const unsigned short %s_portrait_palette[];\n" % portrait_name)
            f.write("extern const unsigned char %s_portrait_tileset[];\n" % portrait_name)
            f.write("extern const unsigned short %s_portrait_oam_right[];\n" % portrait_name)
            f.write("extern const unsigned short %s_portrait_oam_left[];\n" % portrait_name)
            if portrait_in_status_screen_file is not None:
                f.write("extern const unsigned short %s_portrait_in_status_screen_tsa[];\n" % portrait_name)
                f.write("extern const unsigned short %s_portrait_in_status_screen_alpha[][10];\n" % portrait_name)
        source_file = file_base + ".c"
        with open(source_file, 'w') as f:
            f.write(comment)
            f.write("\n#include \"%s.h\"\n" % portrait_name)
            f.write("\nconst unsigned short %s_portrait_palette[] = " % portrait_name)
            f.write(palette.tostring() + ";\n")
            f.write("\nconst unsigned char %s_portrait_tileset[] = " % portrait_name)
            f.write(tileset.tostring().replace("{", "{0x0,0x4,0x10,0x0,", 1) + ";\n")
            f.write("\nconst unsigned short %s_portrait_oam_right[] = {%d, " % (portrait_name, len(oam_right)))
            for i in oam_right:
                f.write(i.tostring() + ", ")
            f.write("};\n")
            f.write("\nconst unsigned short %s_portrait_oam_left[] = {%d, " % (portrait_name, len(oam_left)))
            for i in oam_left:
                f.write(i.tostring() + ", ")
            f.write("};\n")
            if portrait_in_status_screen_file is not None:
                f.write("\nconst unsigned short %s_portrait_in_status_screen_tsa[] = " % portrait_name)
                f.write(status_screen_portrait_map.tostring_reverse() + ";\n")
                f.write("\nconst unsigned short %s_portrait_in_status_screen_alpha[9][10] = " % portrait_name)
                f.write(status_screen_portrait_map.tostring_alpha() + ";\n")
    # todo output binary
    if output_bin:
        pass


if __name__ == "__main__":
    main(sys.argv)
