// by laqieer
// 2017/1/28
// FE7J魔法动画列表

#pragma once

enum {
	MapOnly = 0xFFFE,
	NoSpell = 0xFFFF,
	None = 0,
	ThrowingAxeSpell,
	ArrowSpell,
	Javelin1,
	Javelin2,
	Javelin3,
	Javelin4,
	Javelin5,
	Javelin6,
	Javelin7,
	Javelin8,
	Javelin9,
	Javelin10,
	Javelin11,
	DancePlaySpell1,
	DancePlaySpell2,
	BalistaArrow,
	ExaccusWave,
	SoSFire,
	FlametongueSpell,
	FaHolyDragonStoneSpell,
	IdunDarkDragonStoneSpell,
	FireSpell,
	ElfireSpell,
	ForblazeSpell,
	ThunderSpell,
	BoltingSpell,
	FimbulvetrSpell,
	AircaliburSpell,
	FluxSpell,
	NosferatuSpell,
	LightningSpell,
	PurgeSpell,
	AureolaSpell,
	DivineSpell,
	ApocalypseSpell,
	EclipseSpell,
	FenrirSpell,
	HealSpell,
	MendSpell,
	RecoverSpell,
	PhysicSpell,
	FortifySpell,
	FortifySpellGreen,
	RestoreSpell,
	SilenceSpell,
	SleepSpell,
	HammerneSpell,
	BerserkSpell,
	BarrierSpell,
	PromoBoostSpell,
	ShineSpell,
	LunaSpell,
	ExcaliburSpell,
	GespenstSpell,
	AuraSpell,
	LuceSpell,
	ErishkigalSpell,
	FillaMightSpell,
	NinisGraceSpell,
	ThorIreSpell,
	SetLitanySpell,
	OldTemplateSpell,
	NaglfarSpell,
	ArouSpell,
	IceWorldSpell,
	BloodMoonSpell,
	FireSeaSpell
};