@ Generated by BattleAnimationDumper
@ 2017/08/21 19:16:20

	.include	"../include/BattleAnimation_FE7_0x29_event.inc"

	.section	.rodata
	.align	4
	.global	BattleAnimation_FE7_0x29_data2
	.global	BattleAnimation_FE7_0x29_data1
	.global	BattleAnimation_FE7_0x29_data3
	.global	BattleAnimation_FE7_0x29_data4
	.include	"../include/BattleAnimation_FE7_0x29_OAMInfo.inc"

	.align	4

BattleAnimation_FE7_0x29_data2:

BattleAnimation_FE7_0x29_Mode1:	@ Normal attack (Layered in front of the enemy)

	Cmd 0x3
	Cmd 0x7
	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Show 1, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_1 - BattleAnimation_FE7_0x29_data3, 2
	Show 2, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_2 - BattleAnimation_FE7_0x29_data3, 2
	Show 3, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_3 - BattleAnimation_FE7_0x29_data3, 2
	Show 4, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_4 - BattleAnimation_FE7_0x29_data3, 2
	Show 5, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_5 - BattleAnimation_FE7_0x29_data3, 2
	Show 6, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_6 - BattleAnimation_FE7_0x29_data3, 2
	Show 7, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_7 - BattleAnimation_FE7_0x29_data3, 2
	Show 8, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_8 - BattleAnimation_FE7_0x29_data3, 2
	Show 9, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_10 - BattleAnimation_FE7_0x29_data3, 2
	Show 10, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_12 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x19
	Show 15, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_17 - BattleAnimation_FE7_0x29_data3, 2
	Show 11, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_13 - BattleAnimation_FE7_0x29_data3, 2
	Show 12, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_14 - BattleAnimation_FE7_0x29_data3, 2
	Show 13, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_15 - BattleAnimation_FE7_0x29_data3, 3
	Cmd 0x5
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x6
	Show 16, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_18 - BattleAnimation_FE7_0x29_data3, 4
	Cmd 0xD
	EndMode

BattleAnimation_FE7_0x29_Mode2:	@ Normal attack (Layered behind the enemy)

	Cmd 0x3
	Cmd 0x7
	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Show 1, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_1 - BattleAnimation_FE7_0x29_data3, 2
	Show 2, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_2 - BattleAnimation_FE7_0x29_data3, 2
	Show 3, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_3 - BattleAnimation_FE7_0x29_data3, 2
	Show 4, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_4 - BattleAnimation_FE7_0x29_data3, 2
	Show 5, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_5 - BattleAnimation_FE7_0x29_data3, 2
	Show 6, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_6 - BattleAnimation_FE7_0x29_data3, 2
	Show 7, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_7 - BattleAnimation_FE7_0x29_data3, 2
	Show 8, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_8 - BattleAnimation_FE7_0x29_data3, 2
	Show 9, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_10 - BattleAnimation_FE7_0x29_data3, 2
	Show 10, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_12 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x19
	Show 15, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_17 - BattleAnimation_FE7_0x29_data3, 2
	Show 11, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_13 - BattleAnimation_FE7_0x29_data3, 2
	Show 12, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_14 - BattleAnimation_FE7_0x29_data3, 2
	Show 13, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_15 - BattleAnimation_FE7_0x29_data3, 3
	Cmd 0x5
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x6
	Show 16, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_18 - BattleAnimation_FE7_0x29_data3, 4
	Cmd 0xD
	EndMode

BattleAnimation_FE7_0x29_Mode3:	@ Critical attack (Layered in front of the enemy)

	Cmd 0x3
	Cmd 0x7
	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Show 1, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_1 - BattleAnimation_FE7_0x29_data3, 2
	Show 2, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_2 - BattleAnimation_FE7_0x29_data3, 2
	Show 3, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_3 - BattleAnimation_FE7_0x29_data3, 2
	Show 4, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_4 - BattleAnimation_FE7_0x29_data3, 2
	Show 5, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_5 - BattleAnimation_FE7_0x29_data3, 2
	Show 6, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_6 - BattleAnimation_FE7_0x29_data3, 2
	Show 7, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_7 - BattleAnimation_FE7_0x29_data3, 2
	Show 8, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_8 - BattleAnimation_FE7_0x29_data3, 2
	Show 9, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_10 - BattleAnimation_FE7_0x29_data3, 2
	Show 10, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_12 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x19
	Show 15, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_17 - BattleAnimation_FE7_0x29_data3, 2
	Show 11, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_13 - BattleAnimation_FE7_0x29_data3, 2
	Show 12, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_14 - BattleAnimation_FE7_0x29_data3, 2
	Show 13, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_15 - BattleAnimation_FE7_0x29_data3, 3
	Cmd 0x5
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x6
	Show 16, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_18 - BattleAnimation_FE7_0x29_data3, 4
	Cmd 0xD
	EndMode

BattleAnimation_FE7_0x29_Mode4:	@ Critical attack (Layered behind the enemy)

	Cmd 0x3
	Cmd 0x7
	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Show 1, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_1 - BattleAnimation_FE7_0x29_data3, 2
	Show 2, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_2 - BattleAnimation_FE7_0x29_data3, 2
	Show 3, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_3 - BattleAnimation_FE7_0x29_data3, 2
	Show 4, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_4 - BattleAnimation_FE7_0x29_data3, 2
	Show 5, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_5 - BattleAnimation_FE7_0x29_data3, 2
	Show 6, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_6 - BattleAnimation_FE7_0x29_data3, 2
	Show 7, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_7 - BattleAnimation_FE7_0x29_data3, 2
	Show 8, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_8 - BattleAnimation_FE7_0x29_data3, 2
	Show 9, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_10 - BattleAnimation_FE7_0x29_data3, 2
	Show 10, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_12 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x19
	Show 15, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_17 - BattleAnimation_FE7_0x29_data3, 2
	Show 11, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_13 - BattleAnimation_FE7_0x29_data3, 2
	Show 12, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_14 - BattleAnimation_FE7_0x29_data3, 2
	Show 13, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_15 - BattleAnimation_FE7_0x29_data3, 3
	Cmd 0x5
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x6
	Show 16, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_18 - BattleAnimation_FE7_0x29_data3, 4
	Cmd 0xD
	EndMode

BattleAnimation_FE7_0x29_Mode5:	@ Magic attack

	Cmd 0x3
	Cmd 0x7
	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Show 1, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_1 - BattleAnimation_FE7_0x29_data3, 2
	Show 2, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_2 - BattleAnimation_FE7_0x29_data3, 2
	Show 3, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_3 - BattleAnimation_FE7_0x29_data3, 2
	Show 4, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_4 - BattleAnimation_FE7_0x29_data3, 2
	Show 5, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_5 - BattleAnimation_FE7_0x29_data3, 2
	Show 6, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_6 - BattleAnimation_FE7_0x29_data3, 2
	Show 7, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_7 - BattleAnimation_FE7_0x29_data3, 2
	Show 8, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_8 - BattleAnimation_FE7_0x29_data3, 2
	Show 9, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_10 - BattleAnimation_FE7_0x29_data3, 2
	Show 10, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_12 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x19
	Show 15, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_17 - BattleAnimation_FE7_0x29_data3, 3
	Show 11, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_13 - BattleAnimation_FE7_0x29_data3, 7
	Show 12, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_14 - BattleAnimation_FE7_0x29_data3, 10
	Show 13, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_15 - BattleAnimation_FE7_0x29_data3, 3
	Cmd 0x5
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x6
	Show 16, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_18 - BattleAnimation_FE7_0x29_data3, 4
	Cmd 0xD
	EndMode

BattleAnimation_FE7_0x29_Mode6:	@ Critical magic attack

	Cmd 0x3
	Cmd 0x7
	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Show 1, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_1 - BattleAnimation_FE7_0x29_data3, 2
	Show 2, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_2 - BattleAnimation_FE7_0x29_data3, 2
	Show 3, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_3 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x23
	Show 4, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_4 - BattleAnimation_FE7_0x29_data3, 2
	Show 17, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_19 - BattleAnimation_FE7_0x29_data3, 2
	Show 18, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_20 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x23
	Show 19, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_21 - BattleAnimation_FE7_0x29_data3, 2
	Show 20, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_22 - BattleAnimation_FE7_0x29_data3, 2
	Show 18, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_20 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x23
	Show 19, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_21 - BattleAnimation_FE7_0x29_data3, 2
	Show 20, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_22 - BattleAnimation_FE7_0x29_data3, 2
	Show 22, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_24 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x23
	Show 23, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_25 - BattleAnimation_FE7_0x29_data3, 2
	Show 21, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_23 - BattleAnimation_FE7_0x29_data3, 2
	Show 22, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_24 - BattleAnimation_FE7_0x29_data3, 2
	Show 23, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_25 - BattleAnimation_FE7_0x29_data3, 2
	Show 7, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_7 - BattleAnimation_FE7_0x29_data3, 3
	Show 8, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_8 - BattleAnimation_FE7_0x29_data3, 3
	Show 9, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_10 - BattleAnimation_FE7_0x29_data3, 4
	Show 10, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_12 - BattleAnimation_FE7_0x29_data3, 4
	Cmd 0x19
	Show 15, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_17 - BattleAnimation_FE7_0x29_data3, 5
	Show 11, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_13 - BattleAnimation_FE7_0x29_data3, 7
	Show 12, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_14 - BattleAnimation_FE7_0x29_data3, 15
	Show 13, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_15 - BattleAnimation_FE7_0x29_data3, 3
	Cmd 0x5
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x6
	Show 16, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_18 - BattleAnimation_FE7_0x29_data3, 4
	Cmd 0xD
	EndMode

BattleAnimation_FE7_0x29_Mode7:	@ Close range dodge

	Cmd 0x18
	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0xE
	Show 24, BattleAnimation_FE7_0x29_sheet_3, BattleAnimation_FE7_0x29_frame_R_26 - BattleAnimation_FE7_0x29_data3, 3
	Show 25, BattleAnimation_FE7_0x29_sheet_3, BattleAnimation_FE7_0x29_frame_R_27 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	Show 24, BattleAnimation_FE7_0x29_sheet_3, BattleAnimation_FE7_0x29_frame_R_26 - BattleAnimation_FE7_0x29_data3, 3
	Cmd 0xD
	EndMode

BattleAnimation_FE7_0x29_Mode8:	@ Ranged dodge

	Cmd 0x18
	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0xE
	Show 24, BattleAnimation_FE7_0x29_sheet_3, BattleAnimation_FE7_0x29_frame_R_26 - BattleAnimation_FE7_0x29_data3, 3
	Show 25, BattleAnimation_FE7_0x29_sheet_3, BattleAnimation_FE7_0x29_frame_R_27 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	Show 24, BattleAnimation_FE7_0x29_sheet_3, BattleAnimation_FE7_0x29_frame_R_26 - BattleAnimation_FE7_0x29_data3, 3
	Cmd 0xD
	EndMode

BattleAnimation_FE7_0x29_Mode9:	@ Standing animation

	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	EndMode

BattleAnimation_FE7_0x29_Mode10:	@ Standing animation 2

	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	EndMode

BattleAnimation_FE7_0x29_Mode11:	@ Ranged standing "animation"

	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	EndMode

BattleAnimation_FE7_0x29_Mode12:	@ Dodged attack

	Cmd 0x3
	Cmd 0x7
	Show 0, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_0 - BattleAnimation_FE7_0x29_data3, 1
	Show 1, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_1 - BattleAnimation_FE7_0x29_data3, 2
	Show 2, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_2 - BattleAnimation_FE7_0x29_data3, 2
	Show 3, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_3 - BattleAnimation_FE7_0x29_data3, 2
	Show 4, BattleAnimation_FE7_0x29_sheet_1, BattleAnimation_FE7_0x29_frame_R_4 - BattleAnimation_FE7_0x29_data3, 2
	Show 5, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_5 - BattleAnimation_FE7_0x29_data3, 2
	Show 6, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_6 - BattleAnimation_FE7_0x29_data3, 2
	Show 7, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_7 - BattleAnimation_FE7_0x29_data3, 2
	Show 8, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_8 - BattleAnimation_FE7_0x29_data3, 2
	Show 9, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_10 - BattleAnimation_FE7_0x29_data3, 2
	Show 10, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_12 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x19
	Show 15, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_17 - BattleAnimation_FE7_0x29_data3, 3
	Show 11, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_13 - BattleAnimation_FE7_0x29_data3, 7
	Show 12, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_14 - BattleAnimation_FE7_0x29_data3, 10
	Show 13, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_15 - BattleAnimation_FE7_0x29_data3, 3
	Cmd 0x5
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 1
	Cmd 0x1
	Show 14, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_16 - BattleAnimation_FE7_0x29_data3, 2
	Cmd 0x6
	Show 16, BattleAnimation_FE7_0x29_sheet_2, BattleAnimation_FE7_0x29_frame_R_18 - BattleAnimation_FE7_0x29_data3, 4
	Cmd 0xD
	EndMode

BattleAnimation_FE7_0x29_data1:

	.word	BattleAnimation_FE7_0x29_Mode1 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode2 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode3 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode4 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode5 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode6 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode7 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode8 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode9 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode10 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode11 - BattleAnimation_FE7_0x29_data2
	.word	BattleAnimation_FE7_0x29_Mode12 - BattleAnimation_FE7_0x29_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
