@ Generated by BattleAnimationDumper
@ 2017/10/05 22:42:29

	.include	"BattleAnimationEventDef.inc"

	.include	"../include/BattleAnimation_MyrrhDragon_sheet.inc"

	.section	.rodata
	.align	4
	.global	BattleAnimation_MyrrhDragon_data1
	.global	BattleAnimation_MyrrhDragon_data2
	.global	BattleAnimation_MyrrhDragon_data3
	.global	BattleAnimation_MyrrhDragon_data4
	.include	"../include/BattleAnimation_MyrrhDragon_OAMInfo.inc"

BattleAnimation_MyrrhDragon_data2:

BattleAnimation_MyrrhDragon_Mode1:	@ Normal attack (Layered in front of the enemy)

	SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	@ 衔接不够紧密
	@ Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 5
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Show 1, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_1 - BattleAnimation_MyrrhDragon_data3, 8
	Show 2, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_2 - BattleAnimation_MyrrhDragon_data3, 6
	Show 3, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_3 - BattleAnimation_MyrrhDragon_data3, 3
	Show 4, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_4 - BattleAnimation_MyrrhDragon_data3, 20
	Show 5, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_5 - BattleAnimation_MyrrhDragon_data3, 3
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 6, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_6 - BattleAnimation_MyrrhDragon_data3, 4
	Show 7, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_7 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 8, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_8 - BattleAnimation_MyrrhDragon_data3, 6
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 5
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Trans 3		@ 放在这个位置解除变身动画播放完后会卡死(已修复)
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	@ 动画执行到这里就结束了
	@ 即0x8500000D之后的部分都不会被执行到
	@ Show 6, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_6 - BattleAnimation_MyrrhDragon_data3, 10
	@ Trans 1
	EndMode

BattleAnimation_MyrrhDragon_Mode2:	@ Normal attack (Layered behind the enemy)

	SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	@ Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 5
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 1
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 8
	Show 11, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_11 - BattleAnimation_MyrrhDragon_data3, 6
	Show 11, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_11 - BattleAnimation_MyrrhDragon_data3, 3
	Show 12, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_12 - BattleAnimation_MyrrhDragon_data3, 20
	Show 12, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_12 - BattleAnimation_MyrrhDragon_data3, 3
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 13, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_13 - BattleAnimation_MyrrhDragon_data3, 4
	Show 13, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_13 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 6
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 5
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 1
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	@ Show 6, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_6 - BattleAnimation_MyrrhDragon_data3, 10
	@ Trans 1
	EndMode

BattleAnimation_MyrrhDragon_Mode3:	@ Critical attack (Layered in front of the enemy)

	SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Show 1, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_1 - BattleAnimation_MyrrhDragon_data3, 8
	Show 2, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_2 - BattleAnimation_MyrrhDragon_data3, 6
	@ Cmd 0x7B
	Show 14, BattleAnimation_MyrrhDragon_sheet_6, BattleAnimation_MyrrhDragon_frame_R_14 - BattleAnimation_MyrrhDragon_data3, 2
	Show 15, BattleAnimation_MyrrhDragon_sheet_7, BattleAnimation_MyrrhDragon_frame_R_15 - BattleAnimation_MyrrhDragon_data3, 2
	Show 14, BattleAnimation_MyrrhDragon_sheet_6, BattleAnimation_MyrrhDragon_frame_R_14 - BattleAnimation_MyrrhDragon_data3, 2
	Show 15, BattleAnimation_MyrrhDragon_sheet_7, BattleAnimation_MyrrhDragon_frame_R_15 - BattleAnimation_MyrrhDragon_data3, 2
	Show 14, BattleAnimation_MyrrhDragon_sheet_6, BattleAnimation_MyrrhDragon_frame_R_14 - BattleAnimation_MyrrhDragon_data3, 2
	Show 15, BattleAnimation_MyrrhDragon_sheet_7, BattleAnimation_MyrrhDragon_frame_R_15 - BattleAnimation_MyrrhDragon_data3, 2
	Show 14, BattleAnimation_MyrrhDragon_sheet_6, BattleAnimation_MyrrhDragon_frame_R_14 - BattleAnimation_MyrrhDragon_data3, 2
	Show 15, BattleAnimation_MyrrhDragon_sheet_7, BattleAnimation_MyrrhDragon_frame_R_15 - BattleAnimation_MyrrhDragon_data3, 2
	Show 3, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_3 - BattleAnimation_MyrrhDragon_data3, 3
	Show 4, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_4 - BattleAnimation_MyrrhDragon_data3, 20
	Show 5, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_5 - BattleAnimation_MyrrhDragon_data3, 3
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 6, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_6 - BattleAnimation_MyrrhDragon_data3, 4
	Show 7, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_7 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 8, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_8 - BattleAnimation_MyrrhDragon_data3, 6
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 5
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_MyrrhDragon_Mode4:	@ Critical attack (Layered behind the enemy)

	SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 1
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 8
	Show 11, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_11 - BattleAnimation_MyrrhDragon_data3, 6
	@ Cmd 0x7B
	Show 11, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_11 - BattleAnimation_MyrrhDragon_data3, 2
	Show 13, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_13 - BattleAnimation_MyrrhDragon_data3, 2
	Show 11, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_11 - BattleAnimation_MyrrhDragon_data3, 2
	Show 13, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_13 - BattleAnimation_MyrrhDragon_data3, 2
	Show 11, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_11 - BattleAnimation_MyrrhDragon_data3, 2
	Show 13, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_13 - BattleAnimation_MyrrhDragon_data3, 2
	Show 11, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_11 - BattleAnimation_MyrrhDragon_data3, 2
	Show 13, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_13 - BattleAnimation_MyrrhDragon_data3, 2
	Show 11, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_11 - BattleAnimation_MyrrhDragon_data3, 3
	Show 12, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_12 - BattleAnimation_MyrrhDragon_data3, 20
	Show 12, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_12 - BattleAnimation_MyrrhDragon_data3, 3
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 13, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_13 - BattleAnimation_MyrrhDragon_data3, 4
	Show 13, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_13 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 6
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 5
	Show 10, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_10 - BattleAnimation_MyrrhDragon_data3, 1
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_MyrrhDragon_Mode5:	@ Magic attack

	SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Show 1, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_1 - BattleAnimation_MyrrhDragon_data3, 8
	Show 2, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_2 - BattleAnimation_MyrrhDragon_data3, 6
	Show 3, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_3 - BattleAnimation_MyrrhDragon_data3, 3
	Show 4, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_4 - BattleAnimation_MyrrhDragon_data3, 20
	Show 5, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_5 - BattleAnimation_MyrrhDragon_data3, 3
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 6, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_6 - BattleAnimation_MyrrhDragon_data3, 4
	Show 7, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_7 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 8, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_8 - BattleAnimation_MyrrhDragon_data3, 6
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 5
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_MyrrhDragon_Mode6:	@ Critical magic attack

	SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Show 1, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_1 - BattleAnimation_MyrrhDragon_data3, 8
	Show 2, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_2 - BattleAnimation_MyrrhDragon_data3, 6
	Show 14, BattleAnimation_MyrrhDragon_sheet_6, BattleAnimation_MyrrhDragon_frame_R_14 - BattleAnimation_MyrrhDragon_data3, 2
	Show 15, BattleAnimation_MyrrhDragon_sheet_7, BattleAnimation_MyrrhDragon_frame_R_15 - BattleAnimation_MyrrhDragon_data3, 2
	Show 14, BattleAnimation_MyrrhDragon_sheet_6, BattleAnimation_MyrrhDragon_frame_R_14 - BattleAnimation_MyrrhDragon_data3, 2
	Show 15, BattleAnimation_MyrrhDragon_sheet_7, BattleAnimation_MyrrhDragon_frame_R_15 - BattleAnimation_MyrrhDragon_data3, 2
	Show 14, BattleAnimation_MyrrhDragon_sheet_6, BattleAnimation_MyrrhDragon_frame_R_14 - BattleAnimation_MyrrhDragon_data3, 2
	Show 15, BattleAnimation_MyrrhDragon_sheet_7, BattleAnimation_MyrrhDragon_frame_R_15 - BattleAnimation_MyrrhDragon_data3, 2
	Show 14, BattleAnimation_MyrrhDragon_sheet_6, BattleAnimation_MyrrhDragon_frame_R_14 - BattleAnimation_MyrrhDragon_data3, 2
	Show 15, BattleAnimation_MyrrhDragon_sheet_7, BattleAnimation_MyrrhDragon_frame_R_15 - BattleAnimation_MyrrhDragon_data3, 2
	Show 3, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_3 - BattleAnimation_MyrrhDragon_data3, 3
	Show 4, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_4 - BattleAnimation_MyrrhDragon_data3, 20
	Show 5, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_5 - BattleAnimation_MyrrhDragon_data3, 3
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 6, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_6 - BattleAnimation_MyrrhDragon_data3, 4
	Show 7, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_7 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 8, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_8 - BattleAnimation_MyrrhDragon_data3, 6
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 5
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_MyrrhDragon_Mode7:	@ Close range dodge

	SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_1 - BattleAnimation_MyrrhDragon_data3, 4
	Show 2, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_2 - BattleAnimation_MyrrhDragon_data3, 2
	Show 16, BattleAnimation_MyrrhDragon_sheet_8, BattleAnimation_MyrrhDragon_frame_R_16 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 3
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_MyrrhDragon_Mode8:	@ Ranged dodge

	SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_1 - BattleAnimation_MyrrhDragon_data3, 4
	Show 2, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_2 - BattleAnimation_MyrrhDragon_data3, 2
	Show 16, BattleAnimation_MyrrhDragon_sheet_8, BattleAnimation_MyrrhDragon_frame_R_16 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 3
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_MyrrhDragon_Mode9:	@ Standing animation

	@ SetPal BattleAnimation_MyrrhDragon_pal @ 在这里指定色板会导致攻击动画结束后卡死
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	@ SetPal BattleAnimation_MyrrhDragon_pal @ 在这里指定色板也会导致攻击动画结束后卡死
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	@ SetPal BattleAnimation_MyrrhDragon_pal @ 这里不会被执行到
	EndMode

BattleAnimation_MyrrhDragon_Mode10:	@ Standing animation 2

	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	@ SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_MyrrhDragon_Mode11:	@ Ranged standing "animation"

	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	@ SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_MyrrhDragon_Mode12:	@ Dodged attack

	SetPal BattleAnimation_MyrrhDragon_pal
	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Show 1, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_1 - BattleAnimation_MyrrhDragon_data3, 8
	Show 2, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_2 - BattleAnimation_MyrrhDragon_data3, 6
	Show 3, BattleAnimation_MyrrhDragon_sheet_2, BattleAnimation_MyrrhDragon_frame_R_3 - BattleAnimation_MyrrhDragon_data3, 3
	Show 4, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_4 - BattleAnimation_MyrrhDragon_data3, 20
	Show 5, BattleAnimation_MyrrhDragon_sheet_3, BattleAnimation_MyrrhDragon_frame_R_5 - BattleAnimation_MyrrhDragon_data3, 3
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 6, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_6 - BattleAnimation_MyrrhDragon_data3, 4
	Show 7, BattleAnimation_MyrrhDragon_sheet_4, BattleAnimation_MyrrhDragon_frame_R_7 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 8, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_8 - BattleAnimation_MyrrhDragon_data3, 6
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 9, BattleAnimation_MyrrhDragon_sheet_5, BattleAnimation_MyrrhDragon_frame_R_9 - BattleAnimation_MyrrhDragon_data3, 5
	Show 0, BattleAnimation_MyrrhDragon_sheet_1, BattleAnimation_MyrrhDragon_frame_R_0 - BattleAnimation_MyrrhDragon_data3, 1
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	Trans 3
	EndMode

BattleAnimation_MyrrhDragon_data1:

	.word	BattleAnimation_MyrrhDragon_Mode1 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode2 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode3 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode4 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode5 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode6 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode7 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode8 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode9 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode10 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode11 - BattleAnimation_MyrrhDragon_data2
	.word	BattleAnimation_MyrrhDragon_Mode12 - BattleAnimation_MyrrhDragon_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
