@ Generated by BattleAnimationDumper
@ 2017/10/05 22:34:16

	.include	"BattleAnimationEventDef.inc"

	.include	"../include/BattleAnimation_Myrrh_sheet.inc"

	.section	.rodata
	.align	4
	.global	BattleAnimation_Myrrh_data1
	.global	BattleAnimation_Myrrh_data2
	.global	BattleAnimation_Myrrh_data3
	.global	BattleAnimation_Myrrh_data4
	.include	"../include/BattleAnimation_Myrrh_OAMInfo.inc"

BattleAnimation_Myrrh_data2:

BattleAnimation_Myrrh_Mode1:	@ Normal attack (Layered in front of the enemy)

	Trans 1
	SetPal BattleAnimation_Myrrh_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Show 2, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_2 - BattleAnimation_Myrrh_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Myrrh_Mode2:	@ Normal attack (Layered behind the enemy)

	Trans 1
	SetPal BattleAnimation_Myrrh_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Show 2, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_2 - BattleAnimation_Myrrh_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Myrrh_Mode3:	@ Critical attack (Layered in front of the enemy)

	Trans 1,1
	SetPal BattleAnimation_Myrrh_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Show 2, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_2 - BattleAnimation_Myrrh_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Myrrh_Mode4:	@ Critical attack (Layered behind the enemy)

	Trans 1,1
	SetPal BattleAnimation_Myrrh_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Show 2, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_2 - BattleAnimation_Myrrh_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Myrrh_Mode5:	@ Magic attack

	Trans 1,2
	SetPal BattleAnimation_Myrrh_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Show 2, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_2 - BattleAnimation_Myrrh_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Myrrh_Mode6:	@ Critical magic attack

	Trans 1,3
	SetPal BattleAnimation_Myrrh_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Show 2, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_2 - BattleAnimation_Myrrh_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Myrrh_Mode7:	@ Close range dodge

	Trans 1,4
	SetPal BattleAnimation_Myrrh_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Show 2, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_2 - BattleAnimation_Myrrh_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Myrrh_Mode8:	@ Ranged dodge

	Trans 1,5
	SetPal BattleAnimation_Myrrh_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Show 2, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_2 - BattleAnimation_Myrrh_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Myrrh_Mode9:	@ Standing animation

	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	@ SetPal BattleAnimation_Myrrh_pal
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_Myrrh_Mode10:	@ Standing animation 2

	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	@ SetPal BattleAnimation_Myrrh_pal
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_Myrrh_Mode11:	@ Ranged standing "animation"

	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	@ SetPal BattleAnimation_Myrrh_pal	
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_Myrrh_Mode12:	@ Dodged attack

	Trans 1,9
	SetPal BattleAnimation_Myrrh_pal
	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_0 - BattleAnimation_Myrrh_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Show 2, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_2 - BattleAnimation_Myrrh_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 1, BattleAnimation_Myrrh_sheet_1, BattleAnimation_Myrrh_frame_R_1 - BattleAnimation_Myrrh_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Myrrh_data1:

	.word	BattleAnimation_Myrrh_Mode1 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode2 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode3 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode4 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode5 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode6 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode7 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode8 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode9 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode10 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode11 - BattleAnimation_Myrrh_data2
	.word	BattleAnimation_Myrrh_Mode12 - BattleAnimation_Myrrh_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
