@ Generated by BattleAnimationDumper
@ 2017/10/06 23:26:49

	.include	"BattleAnimationEventDef.inc"

	.include	"../include/BattleAnimation_FaDragon_sheet.inc"

	.section	.rodata
	.align	4
	.global	BattleAnimation_FaDragon_data1
	.global	BattleAnimation_FaDragon_data2
	.global	BattleAnimation_FaDragon_data3
	.global	BattleAnimation_FaDragon_data4
	.include	"../include/BattleAnimation_FaDragon_OAMInfo.inc"

BattleAnimation_FaDragon_data2:

BattleAnimation_FaDragon_Mode1:	@ Normal attack (Layered in front of the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	@ 加过渡帧也没用，这个变身系统本身的问题：trans2之后会有两帧垃圾帧去不掉
	@ Show 14, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_14 - BattleAnimation_FaDragon_data3, 5
	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Show 1, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_1 - BattleAnimation_FaDragon_data3, 3
	Show 2, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_2 - BattleAnimation_FaDragon_data3, 5
	Show 3, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_3 - BattleAnimation_FaDragon_data3, 1
	Show 13, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_13 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 4, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_4 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 5, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_5 - BattleAnimation_FaDragon_data3, 3
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 6, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_6 - BattleAnimation_FaDragon_data3, 2
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_FaDragon_Mode2:	@ Normal attack (Layered behind the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	@ Show 14, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_14 - BattleAnimation_FaDragon_data3, 5
	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Show 1, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_1 - BattleAnimation_FaDragon_data3, 3
	Show 2, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_2 - BattleAnimation_FaDragon_data3, 5
	Show 3, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_3 - BattleAnimation_FaDragon_data3, 1
	Show 13, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_13 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 4, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_4 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 5, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_5 - BattleAnimation_FaDragon_data3, 3
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 6, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_6 - BattleAnimation_FaDragon_data3, 2
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_FaDragon_Mode3:	@ Critical attack (Layered in front of the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Show 9, BattleAnimation_FaDragon_sheet_4, BattleAnimation_FaDragon_frame_R_9 - BattleAnimation_FaDragon_data3, 3
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 20
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 18
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 15
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 3
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 3
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 3
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 9, BattleAnimation_FaDragon_sheet_4, BattleAnimation_FaDragon_frame_R_9 - BattleAnimation_FaDragon_data3, 2
	Show 1, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_1 - BattleAnimation_FaDragon_data3, 3
	Show 2, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_2 - BattleAnimation_FaDragon_data3, 5
	Show 3, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_3 - BattleAnimation_FaDragon_data3, 1
	Show 13, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_13 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 4, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_4 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 5, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_5 - BattleAnimation_FaDragon_data3, 3
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 6, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_6 - BattleAnimation_FaDragon_data3, 2
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_FaDragon_Mode4:	@ Critical attack (Layered behind the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Show 9, BattleAnimation_FaDragon_sheet_4, BattleAnimation_FaDragon_frame_R_9 - BattleAnimation_FaDragon_data3, 3
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 20
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 18
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 15
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 3
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 3
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 3
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 10, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_10 - BattleAnimation_FaDragon_data3, 2
	Show 11, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_11 - BattleAnimation_FaDragon_data3, 2
	Show 12, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_12 - BattleAnimation_FaDragon_data3, 2
	Show 9, BattleAnimation_FaDragon_sheet_4, BattleAnimation_FaDragon_frame_R_9 - BattleAnimation_FaDragon_data3, 2
	Show 1, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_1 - BattleAnimation_FaDragon_data3, 3
	Show 2, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_2 - BattleAnimation_FaDragon_data3, 5
	Show 3, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_3 - BattleAnimation_FaDragon_data3, 1
	Show 13, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_13 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 4, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_4 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 5, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_5 - BattleAnimation_FaDragon_data3, 3
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 6, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_6 - BattleAnimation_FaDragon_data3, 2
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_FaDragon_Mode5:	@ Magic attack

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Show 1, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_1 - BattleAnimation_FaDragon_data3, 3
	Show 2, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_2 - BattleAnimation_FaDragon_data3, 5
	Show 3, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_3 - BattleAnimation_FaDragon_data3, 1
	Show 13, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_13 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 4, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_4 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 5, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_5 - BattleAnimation_FaDragon_data3, 3
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 6, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_6 - BattleAnimation_FaDragon_data3, 2
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_FaDragon_Mode6:	@ Critical magic attack

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Show 1, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_1 - BattleAnimation_FaDragon_data3, 3
	Show 2, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_2 - BattleAnimation_FaDragon_data3, 5
	Show 3, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_3 - BattleAnimation_FaDragon_data3, 1
	Show 13, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_13 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 4, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_4 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 5, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_5 - BattleAnimation_FaDragon_data3, 3
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 6, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_6 - BattleAnimation_FaDragon_data3, 2
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_FaDragon_Mode7:	@ Close range dodge

	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 7, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_7 - BattleAnimation_FaDragon_data3, 3
	Show 8, BattleAnimation_FaDragon_sheet_4, BattleAnimation_FaDragon_frame_R_8 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 7, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_7 - BattleAnimation_FaDragon_data3, 3
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_FaDragon_Mode8:	@ Ranged dodge

	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 7, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_7 - BattleAnimation_FaDragon_data3, 3
	Show 8, BattleAnimation_FaDragon_sheet_4, BattleAnimation_FaDragon_frame_R_8 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 7, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_7 - BattleAnimation_FaDragon_data3, 3
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_FaDragon_Mode9:	@ Standing animation

	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_FaDragon_Mode10:	@ Standing animation 2

	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_FaDragon_Mode11:	@ Ranged standing "animation"

	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_FaDragon_Mode12:	@ Dodged attack

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_0 - BattleAnimation_FaDragon_data3, 1
	Show 1, BattleAnimation_FaDragon_sheet_1, BattleAnimation_FaDragon_frame_R_1 - BattleAnimation_FaDragon_data3, 3
	Show 2, BattleAnimation_FaDragon_sheet_2, BattleAnimation_FaDragon_frame_R_2 - BattleAnimation_FaDragon_data3, 5
	Show 3, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_3 - BattleAnimation_FaDragon_data3, 1
	Show 13, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_13 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 4, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_4 - BattleAnimation_FaDragon_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 5, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_5 - BattleAnimation_FaDragon_data3, 3
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 6, BattleAnimation_FaDragon_sheet_3, BattleAnimation_FaDragon_frame_R_6 - BattleAnimation_FaDragon_data3, 2
	Trans 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_FaDragon_data1:

	.word	BattleAnimation_FaDragon_Mode1 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode2 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode3 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode4 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode5 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode6 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode7 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode8 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode9 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode10 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode11 - BattleAnimation_FaDragon_data2
	.word	BattleAnimation_FaDragon_Mode12 - BattleAnimation_FaDragon_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
