@ Generated by BattleAnimationDumper
@ 2017/10/06 23:27:36

	.include	"BattleAnimationEventDef.inc"

	.include	"../include/BattleAnimation_FaInvers_sheet.inc"

	.section	.rodata
	.align	4
	.global	BattleAnimation_FaInvers_data1
	.global	BattleAnimation_FaInvers_data2
	.global	BattleAnimation_FaInvers_data3
	.global	BattleAnimation_FaInvers_data4
	.include	"../include/BattleAnimation_FaInvers_OAMInfo.inc"

BattleAnimation_FaInvers_data2:

BattleAnimation_FaInvers_Mode1:	@ Normal attack (Layered in front of the enemy)

	SetPal BattleAnimation_FaTrans_pal
	@ SetPal BattleAnimation_FaTrans_pal+0x20
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 9
	Show 1, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_1 - BattleAnimation_FaInvers_data3, 4
	Show 2, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_2 - BattleAnimation_FaInvers_data3, 2
	Show 3, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_3 - BattleAnimation_FaInvers_data3, 2
	Show 4, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_4 - BattleAnimation_FaInvers_data3, 4
	Show 5, BattleAnimation_FaInvers_sheet_2, BattleAnimation_FaInvers_frame_R_5 - BattleAnimation_FaInvers_data3, 4
	Show 6, BattleAnimation_FaInvers_sheet_2, BattleAnimation_FaInvers_frame_R_6 - BattleAnimation_FaInvers_data3, 4
	Show 7, BattleAnimation_FaInvers_sheet_2, BattleAnimation_FaInvers_frame_R_7 - BattleAnimation_FaInvers_data3, 2
	Show 8, BattleAnimation_FaInvers_sheet_2, BattleAnimation_FaInvers_frame_R_8 - BattleAnimation_FaInvers_data3, 2
	@ SetPal BattleAnimation_Fa_pal
	Show 9, BattleAnimation_FaInvers_sheet_2, BattleAnimation_FaInvers_frame_R_9 - BattleAnimation_FaInvers_data3, 2
	Show 10, BattleAnimation_FaInvers_sheet_2, BattleAnimation_FaInvers_frame_R_10 - BattleAnimation_FaInvers_data3, 2
	Show 11, BattleAnimation_FaInvers_sheet_2, BattleAnimation_FaInvers_frame_R_11 - BattleAnimation_FaInvers_data3, 1
	SetPal BattleAnimation_Fa_pal
	Trans 4
	EndMode

BattleAnimation_FaInvers_Mode2:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode3:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode4:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode5:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode6:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode7:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode8:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode9:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode10:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode11:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode
	
BattleAnimation_FaInvers_Mode12:
	Show 0, BattleAnimation_FaInvers_sheet_1, BattleAnimation_FaInvers_frame_R_0 - BattleAnimation_FaInvers_data3, 4
	EndMode


BattleAnimation_FaInvers_data1:

	.word	BattleAnimation_FaInvers_Mode1 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode2 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode3 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode4 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode5 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode6 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode7 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode8 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode9 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode10 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode11 - BattleAnimation_FaInvers_data2
	.word	BattleAnimation_FaInvers_Mode12 - BattleAnimation_FaInvers_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
