@ Generated by BattleAnimationDumper
@ 2017/10/05 22:43:40

	.include	"BattleAnimationEventDef.inc"

	.include	"../include/BattleAnimation_MyrrhTrans_sheet.inc"

	.section	.rodata
	.align	4
	.global	BattleAnimation_MyrrhTrans_data1
	.global	BattleAnimation_MyrrhTrans_data2
	.global	BattleAnimation_MyrrhTrans_data3
	.global	BattleAnimation_MyrrhTrans_data4
	.include	"../include/BattleAnimation_MyrrhTrans_OAMInfo.inc"

BattleAnimation_MyrrhTrans_data2:

BattleAnimation_MyrrhTrans_Mode1:	@ Normal attack (Layered in front of the enemy)

	SetPal BattleAnimation_Myrrh_pal
	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 1
	Show 1, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_1 - BattleAnimation_MyrrhTrans_data3, 6
	Show 2, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_2 - BattleAnimation_MyrrhTrans_data3, 6
	@ Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	SetPal BattleAnimation_MyrrhDragon_pal
	Show 3, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_3 - BattleAnimation_MyrrhTrans_data3, 4
	Show 4, BattleAnimation_MyrrhTrans_sheet_2, BattleAnimation_MyrrhTrans_frame_R_4 - BattleAnimation_MyrrhTrans_data3, 4
	Show 5, BattleAnimation_MyrrhTrans_sheet_2, BattleAnimation_MyrrhTrans_frame_R_5 - BattleAnimation_MyrrhTrans_data3, 4
	Show 6, BattleAnimation_MyrrhTrans_sheet_2, BattleAnimation_MyrrhTrans_frame_R_6 - BattleAnimation_MyrrhTrans_data3, 2
	Show 7, BattleAnimation_MyrrhTrans_sheet_3, BattleAnimation_MyrrhTrans_frame_R_7 - BattleAnimation_MyrrhTrans_data3, 3
	Show 8, BattleAnimation_MyrrhTrans_sheet_3, BattleAnimation_MyrrhTrans_frame_R_8 - BattleAnimation_MyrrhTrans_data3, 3
	Show 9, BattleAnimation_MyrrhTrans_sheet_4, BattleAnimation_MyrrhTrans_frame_R_9 - BattleAnimation_MyrrhTrans_data3, 2
	Show 10, BattleAnimation_MyrrhTrans_sheet_4, BattleAnimation_MyrrhTrans_frame_R_10 - BattleAnimation_MyrrhTrans_data3, 1
	Trans 2
	EndMode

BattleAnimation_MyrrhTrans_Mode2:	@ Normal attack (Layered behind the enemy)

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode3:	@ Critical attack (Layered in front of the enemy)

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode4:	@ Critical attack (Layered behind the enemy)

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode5:	@ Magic attack

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode6:	@ Critical magic attack

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode7:	@ Close range dodge

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode8:	@ Ranged dodge

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode9:	@ Standing animation

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode10:	@ Standing animation 2

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode11:	@ Ranged standing "animation"

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_Mode12:	@ Dodged attack

	Show 0, BattleAnimation_MyrrhTrans_sheet_1, BattleAnimation_MyrrhTrans_frame_R_0 - BattleAnimation_MyrrhTrans_data3, 4
	EndMode

BattleAnimation_MyrrhTrans_data1:

	.word	BattleAnimation_MyrrhTrans_Mode1 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode2 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode3 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode4 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode5 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode6 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode7 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode8 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode9 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode10 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode11 - BattleAnimation_MyrrhTrans_data2
	.word	BattleAnimation_MyrrhTrans_Mode12 - BattleAnimation_MyrrhTrans_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
