@ Generated by BattleAnimationDumper
@ 2017/09/10 20:59:39

	.include	"BattleAnimationEventDef.inc"

	.include	"BattleAnimation_Sain_promoted_Sword_sheet.inc"

	.section	.rodata
	.align	4
	.global	BattleAnimation_Sain_promoted_Sword_data1
	.global	BattleAnimation_Sain_promoted_Sword_data2
	.global	BattleAnimation_Sain_promoted_data3
	.global	BattleAnimation_Sain_promoted_data4
	.include	"BattleAnimation_Sain_promoted_Sword_OAMInfo.inc"

BattleAnimation_Sain_promoted_Sword_data2:

BattleAnimation_Sain_promoted_Sword_Mode1:	@ Normal attack (Layered in front of the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_1 - BattleAnimation_Sain_promoted_data3, 10
	Show 2, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_2 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_3 - BattleAnimation_Sain_promoted_data3, 6
	@ Cmd 0x22 @ Play short sword swinging SFE
	@ Show 4, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 16
	@ Show 5, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_5 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 6, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x4 @ Prepare HP depletion routine; needed to animate return to standing frame after hit
	Cmd 0x15 @ Slight vibration of screen
	Cmd 0x21 @ Play hit SFE (sounds like Knight Lord with sword's hit)
	Cmd 0x1A @ Normal hit
	Show 7, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_7 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 8, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_8 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 9, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_9 - BattleAnimation_Sain_promoted_data3, 2
	Show 29, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_29 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 10, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_10 - BattleAnimation_Sain_promoted_data3, 4
	Show 11, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_11 - BattleAnimation_Sain_promoted_data3, 6
	Show 12, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_12 - BattleAnimation_Sain_promoted_data3, 1
	Show 13, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_13 - BattleAnimation_Sain_promoted_data3, 1
	Show 14, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_14 - BattleAnimation_Sain_promoted_data3, 1
	Show 15, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_15 - BattleAnimation_Sain_promoted_data3, 1
	Show 16, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_16 - BattleAnimation_Sain_promoted_data3, 7
	Show 17, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_17 - BattleAnimation_Sain_promoted_data3, 2
	Show 18, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_18 - BattleAnimation_Sain_promoted_data3, 1
	Show 20, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_20 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x15 @ Slight vibration of screen
	Show 21, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_21 - BattleAnimation_Sain_promoted_data3, 3
	Show 22, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_22 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 23, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_23 - BattleAnimation_Sain_promoted_data3, 5
	Show 24, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_24 - BattleAnimation_Sain_promoted_data3, 5
	Show 25, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_25 - BattleAnimation_Sain_promoted_data3, 6
	Show 26, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_26 - BattleAnimation_Sain_promoted_data3, 8
	Show 27, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_27 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode2:	@ Normal attack (Layered behind the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 1
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 10
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x22 @ Play short sword swinging SFE
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 16
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x4 @ Prepare HP depletion routine; needed to animate return to standing frame after hit
	Cmd 0x15 @ Slight vibration of screen
	Cmd 0x21 @ Play hit SFE (sounds like Knight Lord with sword's hit)
	Cmd 0x1A @ Normal hit
	Show 42, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_42 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 1
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 4
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 6
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 7
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 2
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x15 @ Slight vibration of screen
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 5
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 5
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 6
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 8
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode3:	@ Critical attack (Layered in front of the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_1 - BattleAnimation_Sain_promoted_data3, 10
	Show 2, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_2 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_3 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x22 @ Play short sword swinging SFE
	@ Show 4, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 6
	Show 43, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_43 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x38 @ Play heavy spear spinning SFE
	Show 44, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_44 - BattleAnimation_Sain_promoted_data3, 3
	Show 45, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_45 - BattleAnimation_Sain_promoted_data3, 3
	Show 46, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_46 - BattleAnimation_Sain_promoted_data3, 3
	Show 47, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_47 - BattleAnimation_Sain_promoted_data3, 3
	Show 48, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_48 - BattleAnimation_Sain_promoted_data3, 3
	Show 49, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_49 - BattleAnimation_Sain_promoted_data3, 6
	Show 50, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_50 - BattleAnimation_Sain_promoted_data3, 6
	Show 51, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_51 - BattleAnimation_Sain_promoted_data3, 6
	Show 48, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_48 - BattleAnimation_Sain_promoted_data3, 6
	Show 49, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_49 - BattleAnimation_Sain_promoted_data3, 6
	Show 52, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_52 - BattleAnimation_Sain_promoted_data3, 3
	Show 53, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_53 - BattleAnimation_Sain_promoted_data3, 2
	Show 54, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_54 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 55, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_55 - BattleAnimation_Sain_promoted_data3, 2
	Show 56, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_56 - BattleAnimation_Sain_promoted_data3, 3
	Show 57, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_57 - BattleAnimation_Sain_promoted_data3, 5
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 58, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_58 - BattleAnimation_Sain_promoted_data3, 5
	Show 59, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_59 - BattleAnimation_Sain_promoted_data3, 5
	Show 53, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_53 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 54, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_54 - BattleAnimation_Sain_promoted_data3, 3
	Show 55, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_55 - BattleAnimation_Sain_promoted_data3, 2
	Show 56, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_56 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 57, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_57 - BattleAnimation_Sain_promoted_data3, 5
	Show 58, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_58 - BattleAnimation_Sain_promoted_data3, 5
	Show 59, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_59 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 53, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_53 - BattleAnimation_Sain_promoted_data3, 1
	Show 54, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_54 - BattleAnimation_Sain_promoted_data3, 2
	Show 55, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_55 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 56, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_56 - BattleAnimation_Sain_promoted_data3, 2
	Show 57, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_57 - BattleAnimation_Sain_promoted_data3, 3
	Show 58, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_58 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 59, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_59 - BattleAnimation_Sain_promoted_data3, 3
	Show 53, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_53 - BattleAnimation_Sain_promoted_data3, 1
	Show 54, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_54 - BattleAnimation_Sain_promoted_data3, 2
	Show 55, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_55 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 56, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_56 - BattleAnimation_Sain_promoted_data3, 2
	Show 57, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_57 - BattleAnimation_Sain_promoted_data3, 3
	Show 58, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_58 - BattleAnimation_Sain_promoted_data3, 3
	Show 59, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_59 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 53, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_53 - BattleAnimation_Sain_promoted_data3, 1
	Show 54, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_54 - BattleAnimation_Sain_promoted_data3, 2
	Show 55, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_55 - BattleAnimation_Sain_promoted_data3, 1
	Show 56, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_56 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 57, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_57 - BattleAnimation_Sain_promoted_data3, 3
	Show 58, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_58 - BattleAnimation_Sain_promoted_data3, 3
	Show 59, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_59 - BattleAnimation_Sain_promoted_data3, 3
	Show 53, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_53 - BattleAnimation_Sain_promoted_data3, 1
	Show 54, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_54 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 55, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_55 - BattleAnimation_Sain_promoted_data3, 1
	Show 56, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_56 - BattleAnimation_Sain_promoted_data3, 2
	Show 57, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_57 - BattleAnimation_Sain_promoted_data3, 3
	Show 58, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_58 - BattleAnimation_Sain_promoted_data3, 3
	Show 59, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_59 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x21 @ Play hit SFE (sounds like Knight Lord with sword's hit)
	Cmd 0xC @ Critical hit
	Cmd 0x4 @ Prepare HP depletion routine; needed to animate return to standing frame after hit
	Show 7, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_7 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 8, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_8 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 9, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_9 - BattleAnimation_Sain_promoted_data3, 2
	Show 29, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_29 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 10, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_10 - BattleAnimation_Sain_promoted_data3, 4
	Show 11, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_11 - BattleAnimation_Sain_promoted_data3, 6
	Show 12, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_12 - BattleAnimation_Sain_promoted_data3, 1
	Show 13, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_13 - BattleAnimation_Sain_promoted_data3, 1
	Show 14, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_14 - BattleAnimation_Sain_promoted_data3, 1
	Show 15, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_15 - BattleAnimation_Sain_promoted_data3, 1
	Show 16, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_16 - BattleAnimation_Sain_promoted_data3, 7
	Show 17, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_17 - BattleAnimation_Sain_promoted_data3, 2
	Show 18, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_18 - BattleAnimation_Sain_promoted_data3, 1
	Show 20, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_20 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x15 @ Slight vibration of screen
	Show 21, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_21 - BattleAnimation_Sain_promoted_data3, 3
	Show 22, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_22 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 23, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_23 - BattleAnimation_Sain_promoted_data3, 5
	Show 24, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_24 - BattleAnimation_Sain_promoted_data3, 5
	Show 25, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_25 - BattleAnimation_Sain_promoted_data3, 6
	Show 26, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_26 - BattleAnimation_Sain_promoted_data3, 8
	Show 27, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_27 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode4:	@ Critical attack (Layered behind the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 1
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 10
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x22 @ Play short sword swinging SFE
	Show 33, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_33 - BattleAnimation_Sain_promoted_data3, 6
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x38 @ Play heavy spear spinning SFE
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 3
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 3
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 3
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 3
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 3
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 6
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 6
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 6
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 6
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 6
	Show 38, BattleAnimation_Sain_promoted_Sword_sheet_5, BattleAnimation_Sain_promoted_Sword_frame_R_38 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 5
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 5
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 5
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 5
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 5
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 1
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 1
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x15 @ Slight vibration of screen
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 1
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 1
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 1
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x15 @ Slight vibration of screen
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 1
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 2
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Show 37, BattleAnimation_Sain_promoted_Sword_sheet_6, BattleAnimation_Sain_promoted_Sword_frame_R_37 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x21 @ Play hit SFE (sounds like Knight Lord with sword's hit)
	Cmd 0xC @ Critical hit
	Cmd 0x4 @ Prepare HP depletion routine; needed to animate return to standing frame after hit
	Show 42, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_42 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 2
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 4
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 6
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 7
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 2
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x15 @ Slight vibration of screen
	Show 35, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_35 - BattleAnimation_Sain_promoted_data3, 3
	Show 34, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_34 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 5
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 5
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 6
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 8
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 36, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_36 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode5:	@ Magic attack

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_1 - BattleAnimation_Sain_promoted_data3, 7
	Show 2, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_2 - BattleAnimation_Sain_promoted_data3, 5
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_3 - BattleAnimation_Sain_promoted_data3, 5
	Cmd 0x5 @ Call spell associated with equipped weapon
	Cmd 0x22 @ Play short sword swinging SFE
	@ Show 4, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 28, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_28 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 27, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_27 - BattleAnimation_Sain_promoted_data3, 7
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode6:	@ Critical magic attack

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_1 - BattleAnimation_Sain_promoted_data3, 7
	Show 2, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_2 - BattleAnimation_Sain_promoted_data3, 5
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_3 - BattleAnimation_Sain_promoted_data3, 5
	Cmd 0x22 @ Play short sword swinging SFE
	Show 60, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_60 - BattleAnimation_Sain_promoted_data3, 2
	@ Show 4, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 1
	Show 60, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_60 - BattleAnimation_Sain_promoted_data3, 3
	@ Show 4, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 1
	Show 60, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_60 - BattleAnimation_Sain_promoted_data3, 3
	@ Show 4, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 60, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_60 - BattleAnimation_Sain_promoted_data3, 1
	@ Show 4, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 28, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_28 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 27, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_27 - BattleAnimation_Sain_promoted_data3, 7
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode7:	@ Close range dodge

	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 31, BattleAnimation_Sain_promoted_Sword_sheet_7, BattleAnimation_Sain_promoted_Sword_frame_R_31 - BattleAnimation_Sain_promoted_data3, 3
	Show 32, BattleAnimation_Sain_promoted_Sword_sheet_7, BattleAnimation_Sain_promoted_Sword_frame_R_32 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 31, BattleAnimation_Sain_promoted_Sword_sheet_7, BattleAnimation_Sain_promoted_Sword_frame_R_31 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode8:	@ Ranged dodge

	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 31, BattleAnimation_Sain_promoted_Sword_sheet_7, BattleAnimation_Sain_promoted_Sword_frame_R_31 - BattleAnimation_Sain_promoted_data3, 3
	Show 32, BattleAnimation_Sain_promoted_Sword_sheet_7, BattleAnimation_Sain_promoted_Sword_frame_R_32 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 31, BattleAnimation_Sain_promoted_Sword_sheet_7, BattleAnimation_Sain_promoted_Sword_frame_R_31 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode9:	@ Standing animation

	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode10:	@ Standing animation 2

	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode11:	@ Ranged standing "animation"

	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_Sain_promoted_Sword_Mode12:	@ Dodged attack

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_1 - BattleAnimation_Sain_promoted_data3, 10
	Show 2, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_2 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_3 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x22 @ Play short sword swinging SFE
	@ Show 4, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 14
	@ Show 5, BattleAnimation_Sain_promoted_Sword_sheet_1, BattleAnimation_Sain_promoted_Sword_frame_R_5 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 6, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_4 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x4 @ Prepare HP depletion routine; needed to animate return to standing frame after hit
	Cmd 0x15 @ Slight vibration of screen
	Show 41, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_41 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 8, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_8 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 29, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_29 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 10, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_10 - BattleAnimation_Sain_promoted_data3, 4
	Show 11, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_11 - BattleAnimation_Sain_promoted_data3, 6
	Show 12, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_12 - BattleAnimation_Sain_promoted_data3, 1
	Show 13, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_13 - BattleAnimation_Sain_promoted_data3, 1
	Show 14, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_14 - BattleAnimation_Sain_promoted_data3, 1
	Show 15, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_15 - BattleAnimation_Sain_promoted_data3, 1
	Show 16, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_16 - BattleAnimation_Sain_promoted_data3, 6
	Show 17, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_17 - BattleAnimation_Sain_promoted_data3, 3
	Show 18, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_18 - BattleAnimation_Sain_promoted_data3, 1
	Show 20, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_20 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x15 @ Slight vibration of screen
	Show 21, BattleAnimation_Sain_promoted_Sword_sheet_3, BattleAnimation_Sain_promoted_Sword_frame_R_21 - BattleAnimation_Sain_promoted_data3, 3
	Show 22, BattleAnimation_Sain_promoted_Sword_sheet_2, BattleAnimation_Sain_promoted_Sword_frame_R_22 - BattleAnimation_Sain_promoted_data3, 4
	Cmd 0x1E @ Similar to 0x1D; a bit louder
	Show 23, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_23 - BattleAnimation_Sain_promoted_data3, 5
	Show 24, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_24 - BattleAnimation_Sain_promoted_data3, 5
	Show 25, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_25 - BattleAnimation_Sain_promoted_data3, 6
	Show 26, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_26 - BattleAnimation_Sain_promoted_data3, 8
	Show 27, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_27 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_Sword_sheet_4, BattleAnimation_Sain_promoted_Sword_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_Sword_data1:

	.word	BattleAnimation_Sain_promoted_Sword_Mode1 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode2 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode3 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode4 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode5 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode6 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode7 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode8 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode9 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode10 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode11 - BattleAnimation_Sain_promoted_Sword_data2
	.word	BattleAnimation_Sain_promoted_Sword_Mode12 - BattleAnimation_Sain_promoted_Sword_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
