@ Generated by BattleAnimationDumper
@ 2017/09/10 20:59:18

	.include	"BattleAnimationEventDef.inc"

	.include	"BattleAnimation_Sain_promoted_HandAxe_sheet.inc"

	.section	.rodata
	.align	4
	.global	BattleAnimation_Sain_promoted_HandAxe_data1
	.global	BattleAnimation_Sain_promoted_HandAxe_data2
	.global	BattleAnimation_Sain_promoted_data3
	.global	BattleAnimation_Sain_promoted_data4
	.include	"BattleAnimation_Sain_promoted_HandAxe_OAMInfo.inc"

BattleAnimation_Sain_promoted_HandAxe_data2:

BattleAnimation_Sain_promoted_HandAxe_Mode1:	@ Normal attack (Layered in front of the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_1 - BattleAnimation_Sain_promoted_data3, 10
	Show 2, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_2 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_3 - BattleAnimation_Sain_promoted_data3, 6
	Show 4, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_4 - BattleAnimation_Sain_promoted_data3, 2
	Show 65, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_65 - BattleAnimation_Sain_promoted_data3, 2
	Show 66, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_66 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 67, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_67 - BattleAnimation_Sain_promoted_data3, 2
	Show 68, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_68 - BattleAnimation_Sain_promoted_data3, 2
	Show 69, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_69 - BattleAnimation_Sain_promoted_data3, 1
	Show 70, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_70 - BattleAnimation_Sain_promoted_data3, 1
	Show 71, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_71 - BattleAnimation_Sain_promoted_data3, 1
	Show 72, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_72 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 73, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_73 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x13 @ ? (ranged attack - hand axe for Hector)
	Show 74, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_74 - BattleAnimation_Sain_promoted_data3, 3
	Show 75, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_75 - BattleAnimation_Sain_promoted_data3, 13
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 26, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_26 - BattleAnimation_Sain_promoted_data3, 8
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 27, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_27 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode2:	@ Normal attack (Layered behind the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 1
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 10
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 6
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 2
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 2
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 2
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 2
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 1
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 1
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 1
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x13 @ ? (ranged attack - hand axe for Hector)
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 3
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 13
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 36, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_36 - BattleAnimation_Sain_promoted_data3, 8
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 36, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_36 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 36, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_36 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode3:	@ Critical attack (Layered in front of the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_1 - BattleAnimation_Sain_promoted_data3, 10
	Show 2, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_2 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_3 - BattleAnimation_Sain_promoted_data3, 6
	Show 4, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_4 - BattleAnimation_Sain_promoted_data3, 2
	Show 64, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_64 - BattleAnimation_Sain_promoted_data3, 2
	Show 63, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_63 - BattleAnimation_Sain_promoted_data3, 2
	Show 61, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_61 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x38 @ Play heavy spear spinning SFE
	Show 62, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_62 - BattleAnimation_Sain_promoted_data3, 1
	Show 63, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_63 - BattleAnimation_Sain_promoted_data3, 3
	Show 64, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_64 - BattleAnimation_Sain_promoted_data3, 4
	Show 65, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_65 - BattleAnimation_Sain_promoted_data3, 12
	Show 66, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_66 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 67, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_67 - BattleAnimation_Sain_promoted_data3, 2
	Show 68, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_68 - BattleAnimation_Sain_promoted_data3, 2
	Show 69, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_69 - BattleAnimation_Sain_promoted_data3, 1
	Show 70, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_70 - BattleAnimation_Sain_promoted_data3, 1
	Show 71, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_71 - BattleAnimation_Sain_promoted_data3, 1
	Show 72, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_72 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 73, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_73 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x13 @ ? (ranged attack - hand axe for Hector)
	Show 74, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_74 - BattleAnimation_Sain_promoted_data3, 3
	Show 75, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_75 - BattleAnimation_Sain_promoted_data3, 13
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 26, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_26 - BattleAnimation_Sain_promoted_data3, 8
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 27, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_27 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode4:	@ Critical attack (Layered behind the enemy)

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 1
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 10
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 6
	Show 33, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_33 - BattleAnimation_Sain_promoted_data3, 2
	Show 38, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_38 - BattleAnimation_Sain_promoted_data3, 2
	Show 38, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_38 - BattleAnimation_Sain_promoted_data3, 2
	Show 38, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_38 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x38 @ Play heavy spear spinning SFE
	Show 38, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_38 - BattleAnimation_Sain_promoted_data3, 1
	Show 38, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_38 - BattleAnimation_Sain_promoted_data3, 3
	Show 38, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_38 - BattleAnimation_Sain_promoted_data3, 4
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 12
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 2
	Show 40, BattleAnimation_Sain_promoted_HandAxe_sheet_5, BattleAnimation_Sain_promoted_HandAxe_frame_R_40 - BattleAnimation_Sain_promoted_data3, 2
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 1
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 1
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 1
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x13 @ ? (ranged attack - hand axe for Hector)
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 3
	Show 39, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_39 - BattleAnimation_Sain_promoted_data3, 13
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 36, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_36 - BattleAnimation_Sain_promoted_data3, 8
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 36, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_36 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 36, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_36 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode5:	@ Magic attack

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_1 - BattleAnimation_Sain_promoted_data3, 10
	Show 2, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_2 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_3 - BattleAnimation_Sain_promoted_data3, 6
	Show 4, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_4 - BattleAnimation_Sain_promoted_data3, 2
	Show 65, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_65 - BattleAnimation_Sain_promoted_data3, 2
	Show 66, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_66 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 67, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_67 - BattleAnimation_Sain_promoted_data3, 2
	Show 68, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_68 - BattleAnimation_Sain_promoted_data3, 2
	Show 69, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_69 - BattleAnimation_Sain_promoted_data3, 1
	Show 70, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_70 - BattleAnimation_Sain_promoted_data3, 1
	Show 71, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_71 - BattleAnimation_Sain_promoted_data3, 1
	Show 72, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_72 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 73, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_73 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x13 @ ? (ranged attack - hand axe for Hector)
	Show 74, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_74 - BattleAnimation_Sain_promoted_data3, 3
	Show 75, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_75 - BattleAnimation_Sain_promoted_data3, 13
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 26, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_26 - BattleAnimation_Sain_promoted_data3, 8
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 27, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_27 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode6:	@ Critical magic attack

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_1 - BattleAnimation_Sain_promoted_data3, 10
	Show 2, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_2 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_3 - BattleAnimation_Sain_promoted_data3, 6
	Show 4, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_4 - BattleAnimation_Sain_promoted_data3, 2
	Show 63, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_63 - BattleAnimation_Sain_promoted_data3, 2
	Show 64, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_64 - BattleAnimation_Sain_promoted_data3, 2
	Show 61, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_61 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0x38 @ Play heavy spear spinning SFE
	Show 62, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_62 - BattleAnimation_Sain_promoted_data3, 1
	Show 63, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_63 - BattleAnimation_Sain_promoted_data3, 3
	Show 64, BattleAnimation_Sain_promoted_HandAxe_sheet_4, BattleAnimation_Sain_promoted_HandAxe_frame_R_64 - BattleAnimation_Sain_promoted_data3, 4
	Show 65, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_65 - BattleAnimation_Sain_promoted_data3, 12
	Show 66, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_66 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 67, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_67 - BattleAnimation_Sain_promoted_data3, 2
	Show 68, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_68 - BattleAnimation_Sain_promoted_data3, 2
	Show 69, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_69 - BattleAnimation_Sain_promoted_data3, 1
	Show 70, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_70 - BattleAnimation_Sain_promoted_data3, 1
	Show 71, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_71 - BattleAnimation_Sain_promoted_data3, 1
	Show 72, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_72 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 73, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_73 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x13 @ ? (ranged attack - hand axe for Hector)
	Show 74, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_74 - BattleAnimation_Sain_promoted_data3, 3
	Show 75, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_75 - BattleAnimation_Sain_promoted_data3, 13
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 26, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_26 - BattleAnimation_Sain_promoted_data3, 8
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 27, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_27 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode7:	@ Close range dodge

	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 31, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_31 - BattleAnimation_Sain_promoted_data3, 3
	Show 32, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_32 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 31, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_31 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode8:	@ Ranged dodge

	Cmd 0x2 @ Start of dodge
	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0xE @ Start of dodging frames (should go after standing frame and before dodging animation)
	Show 31, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_31 - BattleAnimation_Sain_promoted_data3, 3
	Show 32, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_32 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 31, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_31 - BattleAnimation_Sain_promoted_data3, 3
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode9:	@ Standing animation

	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode10:	@ Standing animation 2

	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode11:	@ Ranged standing "animation"

	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_Mode12:	@ Dodged attack

	Cmd 0x3 @ Start attack animation; should be followed by 0x07; should head "dodged attack"
	Cmd 0x7 @ Start attack animation; should be preceeded by 0x03
	Show 0, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_0 - BattleAnimation_Sain_promoted_data3, 1
	Show 1, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_1 - BattleAnimation_Sain_promoted_data3, 10
	Show 2, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_2 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0x1D @ Play light horse stepping SFE; pitch increases
	Show 3, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_3 - BattleAnimation_Sain_promoted_data3, 6
	Show 4, BattleAnimation_Sain_promoted_HandAxe_sheet_1, BattleAnimation_Sain_promoted_HandAxe_frame_R_4 - BattleAnimation_Sain_promoted_data3, 2
	Show 65, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_65 - BattleAnimation_Sain_promoted_data3, 2
	Show 66, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_66 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x23 @ Play shorter sword swinging SFE
	Show 67, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_67 - BattleAnimation_Sain_promoted_data3, 2
	Show 68, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_68 - BattleAnimation_Sain_promoted_data3, 2
	Show 69, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_69 - BattleAnimation_Sain_promoted_data3, 1
	Show 70, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_70 - BattleAnimation_Sain_promoted_data3, 1
	Show 71, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_71 - BattleAnimation_Sain_promoted_data3, 1
	Show 72, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_72 - BattleAnimation_Sain_promoted_data3, 2
	Cmd 0x5 @ Call spell associated with equipped weapon
	Show 73, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_73 - BattleAnimation_Sain_promoted_data3, 1
	Cmd 0x13 @ ? (ranged attack - hand axe for Hector)
	Show 74, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_74 - BattleAnimation_Sain_promoted_data3, 3
	Show 75, BattleAnimation_Sain_promoted_HandAxe_sheet_2, BattleAnimation_Sain_promoted_HandAxe_frame_R_75 - BattleAnimation_Sain_promoted_data3, 13
	Cmd 0x1 @ Wait for HP to deplete (freezes if no HP depletion is occurring/has occurred)
	Show 26, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_26 - BattleAnimation_Sain_promoted_data3, 8
	Cmd 0x1C @ Play light horse stepping SFE; pitch decreases
	Show 27, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_27 - BattleAnimation_Sain_promoted_data3, 10
	Cmd 0x6 @ Begin opponent's turn after hit
	Show 30, BattleAnimation_Sain_promoted_HandAxe_sheet_3, BattleAnimation_Sain_promoted_HandAxe_frame_R_30 - BattleAnimation_Sain_promoted_data3, 6
	Cmd 0xD @ End of dodge animation (should have an 0x01 command before it and after a preceding 0x0E)
	EndMode

BattleAnimation_Sain_promoted_HandAxe_data1:

	.word	BattleAnimation_Sain_promoted_HandAxe_Mode1 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode2 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode3 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode4 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode5 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode6 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode7 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode8 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode9 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode10 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode11 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	BattleAnimation_Sain_promoted_HandAxe_Mode12 - BattleAnimation_Sain_promoted_HandAxe_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
