@ Generated by BattleAnimationDumper
@ 2017/10/06 23:27:19

	.include	"BattleAnimationEventDef.inc"

	.include	"../include/BattleAnimation_FaTrans_sheet.inc"

	.section	.rodata
	.align	4
	.global	BattleAnimation_FaTrans_data1
	.global	BattleAnimation_FaTrans_data2
	.global	BattleAnimation_FaTrans_data3
	.global	BattleAnimation_FaTrans_data4
	.include	"../include/BattleAnimation_FaTrans_OAMInfo.inc"

BattleAnimation_FaTrans_data2:

BattleAnimation_FaTrans_Mode1:	@ Normal attack (Layered in front of the enemy)

	@ SetPal BattleAnimation_FaTrans_pal
	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 1
	Show 1, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_1 - BattleAnimation_FaTrans_data3, 1
	Show 2, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_2 - BattleAnimation_FaTrans_data3, 1
	Show 3, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_3 - BattleAnimation_FaTrans_data3, 1
	Show 4, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_4 - BattleAnimation_FaTrans_data3, 1
	Show 5, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_5 - BattleAnimation_FaTrans_data3, 1
	Show 6, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_6 - BattleAnimation_FaTrans_data3, 1
	Cmd 0x25 @ Play wing flap SFE
	Show 7, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_7 - BattleAnimation_FaTrans_data3, 1
	Show 8, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_8 - BattleAnimation_FaTrans_data3, 1
	Show 9, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_9 - BattleAnimation_FaTrans_data3, 1
	Show 10, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_10 - BattleAnimation_FaTrans_data3, 1
	Show 11, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_11 - BattleAnimation_FaTrans_data3, 1
	Show 12, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_12 - BattleAnimation_FaTrans_data3, 7
	@ SetPal BattleAnimation_FaDragon_pal
	@ SetPal BattleAnimation_FaTrans_pal+0x20
	Show 13, BattleAnimation_FaTrans_sheet_2, BattleAnimation_FaTrans_frame_R_13 - BattleAnimation_FaTrans_data3, 2
	Show 14, BattleAnimation_FaTrans_sheet_2, BattleAnimation_FaTrans_frame_R_14 - BattleAnimation_FaTrans_data3, 2
	Show 15, BattleAnimation_FaTrans_sheet_2, BattleAnimation_FaTrans_frame_R_15 - BattleAnimation_FaTrans_data3, 3
	Show 16, BattleAnimation_FaTrans_sheet_2, BattleAnimation_FaTrans_frame_R_16 - BattleAnimation_FaTrans_data3, 2
	Show 17, BattleAnimation_FaTrans_sheet_2, BattleAnimation_FaTrans_frame_R_17 - BattleAnimation_FaTrans_data3, 3
	Show 18, BattleAnimation_FaTrans_sheet_3, BattleAnimation_FaTrans_frame_R_18 - BattleAnimation_FaTrans_data3, 2
	Show 19, BattleAnimation_FaTrans_sheet_3, BattleAnimation_FaTrans_frame_R_19 - BattleAnimation_FaTrans_data3, 2
	Show 20, BattleAnimation_FaTrans_sheet_3, BattleAnimation_FaTrans_frame_R_20 - BattleAnimation_FaTrans_data3, 2
	Show 21, BattleAnimation_FaTrans_sheet_4, BattleAnimation_FaTrans_frame_R_21 - BattleAnimation_FaTrans_data3, 1
	SetPal BattleAnimation_FaDragon_pal
	Trans 2
	EndMode

BattleAnimation_FaTrans_Mode2:	@ Normal attack (Layered behind the enemy)

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode3:	@ Critical attack (Layered in front of the enemy)

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode4:	@ Critical attack (Layered behind the enemy)

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode5:	@ Magic attack

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode6:	@ Critical magic attack

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode7:	@ Close range dodge

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode8:	@ Ranged dodge

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode9:	@ Standing animation

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode10:	@ Standing animation 2

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode11:	@ Ranged standing "animation"

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_Mode12:	@ Dodged attack

	Show 0, BattleAnimation_FaTrans_sheet_1, BattleAnimation_FaTrans_frame_R_0 - BattleAnimation_FaTrans_data3, 4
	EndMode

BattleAnimation_FaTrans_data1:

	.word	BattleAnimation_FaTrans_Mode1 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode2 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode3 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode4 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode5 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode6 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode7 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode8 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode9 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode10 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode11 - BattleAnimation_FaTrans_data2
	.word	BattleAnimation_FaTrans_Mode12 - BattleAnimation_FaTrans_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
