@ Generated by BattleAnimationDumper
@ 2017/08/27 19:52:53

	.include	"BattleAnimationEventDef.inc"

	.include	"../include/PriscillaAnimationTest_sheet.inc"

	.section	.rodata
	.align	4
	.global	PriscillaAnimationTest_data1
	.global	PriscillaAnimationTest_data2
	.global	PriscillaAnimationTest_data3
	.global	PriscillaAnimationTest_data4
	.include	"../include/PriscillaAnimationTest_OAMInfo.inc"

PriscillaAnimationTest_data2:

PriscillaAnimationTest_Mode1:	@ Normal attack (Layered in front of the enemy)

	Cmd 0x3
	Cmd 0x7
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x5
	Show 2, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_2 - PriscillaAnimationTest_data3, 5
	Cmd 0x1
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x6
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Cmd 0xD
	EndMode

PriscillaAnimationTest_Mode2:	@ Normal attack (Layered behind the enemy)

	Cmd 0x3
	Cmd 0x7
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x5
	Show 2, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_2 - PriscillaAnimationTest_data3, 5
	Cmd 0x1
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x6
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Cmd 0xD
	EndMode

PriscillaAnimationTest_Mode3:	@ Critical attack (Layered in front of the enemy)

	Cmd 0x3
	Cmd 0x7
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x5
	Show 2, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_2 - PriscillaAnimationTest_data3, 5
	Cmd 0x1
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x6
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Cmd 0xD
	EndMode

PriscillaAnimationTest_Mode4:	@ Critical attack (Layered behind the enemy)

	Cmd 0x3
	Cmd 0x7
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x5
	Show 2, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_2 - PriscillaAnimationTest_data3, 5
	Cmd 0x1
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x6
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Cmd 0xD
	EndMode

PriscillaAnimationTest_Mode5:	@ Magic attack

	Cmd 0x3
	Cmd 0x7
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x5
	Show 2, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_2 - PriscillaAnimationTest_data3, 5
	Cmd 0x1
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x6
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Cmd 0xD
	EndMode

PriscillaAnimationTest_Mode6:	@ Critical magic attack

	Cmd 0x3
	Cmd 0x7
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x5
	Show 2, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_2 - PriscillaAnimationTest_data3, 5
	Cmd 0x1
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x6
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Cmd 0xD
	EndMode

PriscillaAnimationTest_Mode7:	@ Close range dodge

	Cmd 0x2
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 1
	Cmd 0xE
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x1
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_2 - PriscillaAnimationTest_data3, 3
	Cmd 0xD
	EndMode

PriscillaAnimationTest_Mode8:	@ Ranged dodge

	Cmd 0x2
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 1
	Cmd 0xE
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x1
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_2 - PriscillaAnimationTest_data3, 3
	Cmd 0xD
	EndMode

PriscillaAnimationTest_Mode9:	@ Standing animation

	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 1
	Cmd 0x1
	EndMode

PriscillaAnimationTest_Mode10:	@ Standing animation 2

	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 1
	Cmd 0x1
	EndMode

PriscillaAnimationTest_Mode11:	@ Ranged standing "animation"

	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 1
	Cmd 0x1
	EndMode

PriscillaAnimationTest_Mode12:	@ Dodged attack

	Cmd 0x3
	Cmd 0x7
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x5
	Show 2, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_2 - PriscillaAnimationTest_data3, 5
	Cmd 0x1
	Show 1, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_1 - PriscillaAnimationTest_data3, 3
	Cmd 0x6
	Show 0, PriscillaAnimationTest_sheet_1, PriscillaAnimationTest_frame_R_0 - PriscillaAnimationTest_data3, 5
	Cmd 0xD
	EndMode

PriscillaAnimationTest_data1:

	.word	PriscillaAnimationTest_Mode1 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode2 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode3 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode4 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode5 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode6 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode7 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode8 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode9 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode10 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode11 - PriscillaAnimationTest_data2
	.word	PriscillaAnimationTest_Mode12 - PriscillaAnimationTest_data2
	.word	0,0,0,0,0,0,0,0,0,0,0,0

	.end
